### Đăng ký
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "username":"messi",
    "password":"vykt2000",
    "confirmPassword":"vykt2000",
    "email":"lnhv.26112000@gmail.com"
}


#### Đăng nhập
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "username":"ronaldo",
    "password":"vykt2000"
}

### get room by Id
GET  http://localhost:4000/api/room/get-room/60fe7afbeda70d08d04e66d2


### create room
POST http://localhost:4000/api/room/create-room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmU1ODRlMmQ0ZjBmNDAwY2I1ODIxNyIsImVtYWlsIjoibG5odi4yNjExMjAwMEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjI3NjU1ODgzLCJleHAiOjE2Mjg4NjU0ODN9.kLQ94htH_s95R5S2qp7cxDubMMY8nzPPWzrEdq-k05A
Content-Type: application/json

{
    "userId":"61040ddbae25af1330946b67"
}



### get my rooms
GET http://localhost:4000/api/room/get-my-rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmU1ODRlMmQ0ZjBmNDAwY2I1ODIxNyIsImVtYWlsIjoibG5odi4yNjExMjAwMEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjI3NDYyMjE3LCJleHAiOjE2Mjg2NzE4MTd9.Qga4emQtUvvtVp7tGwV32E8anzCeubZdKz88axTEQ70

### send message
POST http://localhost:4000/api/message/6104135c62d3281e4074fed3/send-message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMDQwN2Y1ZDEzNzcyMzlhNDkxNTg3ZSIsImVtYWlsIjoibG5odi4yNjExMjAwMEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InJvbmFsZG8iLCJpYXQiOjE2Mjc2NTcyMDAsImV4cCI6MTYyODg2NjgwMH0.RAdW8IapPLs3YvxlJhJKra2ExmbgFjuPYUduEzWiqag
Content-Type: application/json

{
    "body":"Lorem Ipsum is simply dummy text of the printing."
}

### get message by id eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmU1ZmI1ZDcxZGY4MWU4Y2M1NTlkZCIsImVtYWlsIjoibG5odi4yNjExMjAwMEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlMiIsImlhdCI6MTYyNzYzMzc4NiwiZXhwIjoxNjI4ODQzMzg2fQ.EMvfCpZqzOkDM4wtJlwsadkRvGiLlMLYojRBie4ljq0
GET http://localhost:4000/api/message/60fe8372aa41173eec747ad8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmU1ODRlMmQ0ZjBmNDAwY2I1ODIxNyIsImVtYWlsIjoibG5odi4yNjExMjAwMEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjI3NDYyMjE3LCJleHAiOjE2Mjg2NzE4MTd9.Qga4emQtUvvtVp7tGwV32E8anzCeubZdKz88axTEQ70