### Đăng ký
POST http://localhost:4000/api/auth/register
Content-Type: application/json

{
    "username":"vyhungle",
    "password":"vykt2000",
    "confirmPassword":"vykt2000",
    "email":"lnhv.26112000@gmail.com"
}


#### Đăng nhập
POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
    "username":"vyhungle",
    "password":"vykt2000"
}

### get room by Id
GET  http://localhost:4000/api/room/get-room/60fe7afbeda70d08d04e66d2


### create room
POST http://localhost:4000/api/room/create-room
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmU1ODRlMmQ0ZjBmNDAwY2I1ODIxNyIsImVtYWlsIjoibG5odi4yNjExMjAwMEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjI3Mjg0MDE4LCJleHAiOjE2Mjg0OTM2MTh9.EuQLY-vWbfpYj4H5R_OxcN7zU1gLz0pObm9Fr-qwnvc
Content-Type: application/json

{
    "userId":"60fe5fb5d71df81e8cc559dd"
}



### get my rooms
GET http://localhost:4000/api/room/get-my-rooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmU1ODRlMmQ0ZjBmNDAwY2I1ODIxNyIsImVtYWlsIjoibG5odi4yNjExMjAwMEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjI3NDYyMjE3LCJleHAiOjE2Mjg2NzE4MTd9.Qga4emQtUvvtVp7tGwV32E8anzCeubZdKz88axTEQ70

### send message
POST http://localhost:4000/api/message/60fe8372aa41173eec747ad8/send-message
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmU1ODRlMmQ0ZjBmNDAwY2I1ODIxNyIsImVtYWlsIjoibG5odi4yNjExMjAwMEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjI3Mjg0MDE4LCJleHAiOjE2Mjg0OTM2MTh9.EuQLY-vWbfpYj4H5R_OxcN7zU1gLz0pObm9Fr-qwnvc
Content-Type: application/json

{
    "body":"hello"
}

### get message by id
GET http://localhost:4000/api/message/60fe8372aa41173eec747ad8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwZmU1ODRlMmQ0ZjBmNDAwY2I1ODIxNyIsImVtYWlsIjoibG5odi4yNjExMjAwMEBnbWFpbC5jb20iLCJ1c2VybmFtZSI6InZ5aHVuZ2xlIiwiaWF0IjoxNjI3NDYyMjE3LCJleHAiOjE2Mjg2NzE4MTd9.Qga4emQtUvvtVp7tGwV32E8anzCeubZdKz88axTEQ70